### ISSUE TITLE
About the dataset label problem

### ISSUE THREAD

**Issue by aniyajerry** [RuiyangJu/YOLOv8_Global_Context_Fracture_Detection#3]
Hello author, I have converted the json format in the data set to txt format, but there are many warnings when the data set is checked, as follows:
train: WARNING ⚠️ /home/jerry/pytemp/Dataset/GRAZPEDWRI-DX/train/images/6045_0786272019_02_WRI-L1_M014.png: ignoring corrupt image/label: negative label values [ -0.0063091   -0.095128]
train: WARNING ⚠️ /home/jerry/pytemp/Dataset/GRAZPEDWRI-DX/train/images/6060_0589184569_06_WRI-L1_M015.png: ignoring corrupt image/label: negative label values [  -0.045455]
...
I don't know how to fix it. Have you ever had this problem?

**Comment by RuiyangJu** [comment]
Hello,
The data we provide is only an example. You can find the complete dataset in the following link:

>https://figshare.com/articles/dataset/GRAZPEDWRI-DX/14825193

And then just replace them in the “GRAZPEDWRI-DX” folder.
